name: Auto Merge

on:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Merge changes
        run: |
          git checkout main  # Mude para a branch principal do repositório fork
          git pull https://github.com/deiwdofficial/smklimatiza.git main
          git push origin main
